### ISSUE TITLE
[Improve] local docker build 속도 개선

### ISSUE THREAD

**Issue by jyeonjyan** [themoment-team/HiRecruit-server#252]
### 11 sec -> 1.5 sec
```
hardware spec
- MacBook Pro (16-inch, 2019)
- 2.3 GHz 8-Core Intel Core i9
- 16 GB 2667 MHz DDR4
```

![image](https://user-images.githubusercontent.com/67095821/180388535-939bebee-c2e5-45c7-afd8-f7a12cc07a1c.png)

**Comment by jyeonjyan** [comment]
## 놀랍게도 Prod 획기적인 성능 개선이 이루어졌다..

`docker build`시 `hr-app layering` 한 부분이 all caching 되었다. **at 2022.07.22**

<img width="400" alt="CleanShot 2022-07-22 at 17 52 05@2x" src="https://user-images.githubusercontent.com/67095821/180402489-b0d8c94b-23e0-4991-a74d-d0efe4680966.png">
<img width="400" alt="CleanShot 2022-07-22 at 17 52 14@2x" src="https://user-images.githubusercontent.com/67095821/180402499-6d59f508-0295-4006-baf3-b952fc64a44e.png">

**Comment by jyeonjyan** [comment]
매번 드라마틱한 build 속도를 체감할 수 없는 이유는 
github action 은 실행될 때마다 매번 새로운 인스턴스에서 실행하게 되는데.
cache storage 가 10GB, 7 days 보관 정책으로 제한되어 있음.
> https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy

**Comment by codnstj** [comment]
성능 개선 회고

### Problems : Build & Deploy 시간이 총합 약 16 분 정도 걸려 배포하는데 시간이 너무 오래 걸림

이문제의 원인은 이러함 

->  Github Action 에서 ProdCD 스크립트 중 Deploy  TaskDefinition Deploy 단계 가 있는데  	 이 단계 에서 현재 이미 올라가있는 컨테이너가 종료되는 시간인 deregistration_delay.time 의 Default 값이 5분이다. 하지만 컨테이너 가 생성된후 실행까지는 약 2분에서 3분 정도가 걸린다. 

즉 

컨테이너가 테스크로 생성이 됨 -> ECS 에서 설정해놓은 로드밸런서의 대상그룹에 새로 구성한 컨테이너가 추가됨 -> 기존 컨테이너가 삭제됨

이런 단계로 배포가 되는데 로드밸런서에서 대상그룹에 새로운 컨테이너를 추가하고 이를 initial 하는데 시간이 좀 걸리므로 약 3분정도가 소요된다.  최종적으로 기존 워크 플로우에서는 

컨테이너 실행시각(약 1~2분) + 기존 컨테이너 삭제시각 (5분) + 로드밸런서 Initialize 시간 ( 약 30초 ) 정도가 포함되어 약 6 ~ 6분 30초 정도가 걸리게 되었는데

이를  
컨테이너 실행시각(약 1~2분) + 기존 컨테이너 삭제시각 (5초) + 로드밸런서 Initialize 시간 ( 약 1분 ) 정도가 포함되어 약 2분으로 줄였다.

**Comment by jyeonjyan** [comment]
굿굿 이 이슈는 long-term performance check가 필요해 보여서 closed 하지 않고 open 해두겠습니다.
추가적인 실험이나 개선사항 있으시면 해당 이슈 언급하여 PR 날려주세요 ! @codnstj

**Comment by jyeonjyan** [comment]
와 ㅋㅋㅋㅋ 사람들의 불편함은 다 똑같나 봅니다.
저도 현재 repository, branch, actions 에서 사용되는 활성화 캐시가 뭔지, 사이즈가 어떻게 되는지 알려주는 `automation script + bot` 을 디코 노티로 만들었는데.. 
비슷한 불편함을 개선하기 위해 생긴 actions 프로젝트가 8시간 전에 public으로 세상에 나타났습니다.. 😅
https://github.com/actions/gh-actions-cache

**Comment by jyeonjyan** [comment]
Solved ! 🎉
