### ISSUE TITLE
[BUG] Bug Report

### ISSUE THREAD

**Issue by JiHoonAHN** [themoment-team/HiRecruit-server#272]
## 버그 개요
> 버그에 대해 알려주세요!

web page에서 로그인 버튼을 누르면 503 Service Temporarily Unavailable 이라는 에러가 발생합니다.
&& 
List 가 조회되지 않습니다.

## 재현 방법
저희가 확인할 수 있도록 어떤 행동을 했을 때 버그가 발생하는지 알려주세요!

> 1. 웹을 들어왔을때 List가 조회되지 않습니다.
> 2. 로그인을 누르면 503 Service Temporarily Unavailable가 발생합니다.

## 스크린샷
> 저희가 문제를 정확히 알 수 있도록 스크린샷을 통해 도와주세요
영상으로 첨부합니다. 

https://user-images.githubusercontent.com/68891494/182002403-fe7c5faf-ec3a-4cba-90df-a4246fda6b71.mov

**Comment by jyeonjyan** [comment]
안녕하세요.

이 이슈는 #271 에서 해결중인 사안과 동일합니다.
빠르게 해결하여 더 안정적인 서비스로 보답하겠습니다.

감사합니다.
