### ISSUE TITLE
[BUG] Bug Report

### ISSUE THREAD

**Issue by jyeonjyan** [themoment-team/HiRecruit-server#90]
## 버그 개요
jar 파일을 실행할 때 default profile을 요구 함.

## 재현 방법

```
cd ~/HiRecruit-server/build/libs
java -jar hirecruit-1.0.jar
```

## 스크린샷

![CleanShot 2022-05-31 at 19 02 23@2x](https://user-images.githubusercontent.com/67095821/171148832-d4e210a5-8549-4534-aa85-0bd6b00cf59a.png)

**Comment by siwony** [comment]
#92 #94 에서 해결된 이슈입니다.
